### ISSUE TITLE
git add --all throws error on extra directory contents

### ISSUE THREAD

**Issue by glennholloway** [cs50/submit50#38]
A CS50x user of `submit50-2.1.4` reported getting the "Something is wrong ..." error at the point where the script runs `git add --all`. He was submitting from a directory with several files unrelated to the problem being submitted. I was able to reproduce the error, as shown below. When I then removed the extraneous files, I was able to submit with no problem.
```
~/workspace/pset3/ $ submit50 --verbose 2017/x/find/less
GitHub username: glennholloway
GitHub password: ***********      
Authentication code: 600525
git clone --bare https://glennholloway@github.com/submit50/glennholloway /tmp/tmpmdp22r_1
Cloning into bare repository '/tmp/tmpmdp22r_1'...
Password for 'https://glennholloway@github.com': 
remote: Counting objects: 52, done.        
remote: Compressing objects: 100% (3/3), done.        
remote: Total 52 (delta 1), reused 0 (delta 0), pack-reused 49        
Unpacking objects: 100% (52/52), done.
Checking connectivity... done.
git config user.email glennholloway@users.noreply.github.com
git config user.name glennholloway
git symbolic-ref HEAD refs/heads/cs50/2017/x/find/less
git config core.excludesFile /tmp/tmphfx347xy
git config core.ignorecase true
git add --all
  File "/opt/cs50/bin/submit50", line 465, in <module>
    main()
  File "/opt/cs50/bin/submit50", line 89, in main
    submit(args["args"][0])
  File "/opt/cs50/bin/submit50", line 228, in submit
    run("git add --all")
  File "/opt/cs50/bin/submit50", line 401, in run
    raise Error()
Sorry, something's wrong! Let sysadmins@cs50.harvard.edu know!
Submission cancelled.
~/workspace/pset3/ $ version50
98
~/workspace/pset3/ $ ls -a
./   Makefile   caesar.c   find.c    generate.c    helpers.c  makefile
../  Untitled1  fifteen.c  generate  helpers.[hc]  helpers.h
~/workspace/pset3/ $ 
```

**Comment by kzidane** [comment]
This appears to be caused by [submit50L#38](https://github.com/cs50/submit50/blob/8ef07ccc68982e618e6bc87dd868920a9bf23271/submit50#L385)

    run("git config core.ignorecase true")

For example, if both `Makefile` and `makefile` are present, `git` will refuse to add both of them at once, because it considers one of them alias to the other.

> fatal: Will not add file alias 'makefile' ('Makefile' already exists in index)

@brianyu28 recall why you added this?  Hoping to fix before releasing 2.1.6.

**Comment by brianyu28** [comment]
Hm, this was just a line that I translated over form the original implementation here:

https://github.com/cs50/submit50/blob/4d997dfa287ff50cf4e9d33967791ac36b75c7b9/opt/cs50/submit50/bin/submit50#L330

I think (correct me if I'm wrong, @dmalan) that the goal here was so that if someone had a file matching our exclude file but not matching its case (someone had `Water.c` for pset1, for instance), that they'd still be able to submit?

**Comment by dmalan** [comment]
@brianyu28's thought sounds right. But now that we've changed the semantics of `#` to mean "required" instead of "recommended," aok to remove that line methinks!
