### ISSUE TITLE
should we be calling pexpect.run directly?

### ISSUE THREAD

**Issue by dmalan** [cs50/submit50#49]
In https://github.com/cs50/submit50/blob/master/submit50#L211, we call `pexpect.run` directly, but should that be a call to our own `run` method? To facilitate such, do we need to change `run` to return not only `command_output` but a `statuscode`?

**Comment by brianyu28** [comment]
We no longer call `pexpect.run` directly since we've eliminated `--checkout`, so it doesn't seem like there's a need to output `statuscode` so far (since if `statuscode` isn't 0, we'll just raise an error with an appropriate message) yet, but if it comes up again we can probably change our `run` function to do that.
