### ISSUE TITLE
easy way to install dependencies in dev environments

### ISSUE THREAD

**Issue by dmalan** [cs50/submit50#66]
Rather than having to install the package itself, is there a simple way to install

```
"getch", "pexpect>=4.0", "requests", "termcolor"
```

in dev environments, in a manner akin to `pip install -r requirements`?

**Comment by kzidane** [comment]
But wouldn't you still have to manually install packages in the requirements file? Using requirements file instead of `install_requires` in `setup.py` has its advantages (e.g., specifying custom repos to install from), but that's not useful for this package meanwhile. A deal-breaker though might be that requirements files are not automatically analyzed by `pip` during installation per https://packaging.python.org/requirements/:

> Whereas `install_requires` metadata is automatically analyzed by `pip` during an install, requirements files are not, and only are used when a user specifically installs them using `pip install -r`.

What's wrong with `python setup.py develop`?
